FROM mcr.microsoft.com/mssql/server:2022-latest

# Switch to root to install packages
USER root

# Install dependencies and mssql-server-fts
RUN apt-get update && \
    apt-get install -yq gnupg2 curl apt-transport-https && \
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list > /etc/apt/sources.list.d/mssql-server-2022.list && \
    apt-get update && \
    apt-get install -y mssql-server-fts && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Switch back to mssql user
USER mssql
