// <auto-generated />
using System;
using AcikIstihbarat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcikIstihbarat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801230008_AddFullTextSearch")]
    partial class AddFullTextSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Haber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HaberId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HaberBaslik");

                    b.Property<string>("HtmlIcerigi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HaberTamMetin");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("HaberHaberTuruId");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("HaberKullaniciId");

                    b.Property<string>("LegacyResimAdresi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HaberResimAdresi");

                    b.Property<bool>("Mansetmi")
                        .HasColumnType("bit")
                        .HasColumnName("HaberMansetMi");

                    b.Property<int>("Okunma")
                        .HasColumnType("int")
                        .HasColumnName("HaberOkunma");

                    b.Property<bool>("Onay")
                        .HasColumnType("bit")
                        .HasColumnName("HaberOnay");

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("HaberSaat");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit")
                        .HasColumnName("HaberSilindiMi");

                    b.Property<string>("Spot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HaberOnIzlemeMetni");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("HaberTarih");

                    b.Property<bool>("YorumaAcikMi")
                        .HasColumnType("bit")
                        .HasColumnName("HaberYorumaAcikMi");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Haber");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.HaberKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("HaberKategorileri");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.HaberMedya", b =>
                {
                    b.Property<int>("HaberId")
                        .HasColumnType("int");

                    b.Property<int>("MedyaId")
                        .HasColumnType("int");

                    b.Property<bool>("OncuResimMi")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("HaberId", "MedyaId");

                    b.HasIndex("MedyaId");

                    b.ToTable("HaberMedyalar");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Medya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnahtarKelimeler")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DosyaUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MedyaKutuphanesi");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarID"));

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("YazarID");

                    b.ToTable("Yazarlar");

                    b.HasData(
                        new
                        {
                            YazarID = 1,
                            YazarAdi = "Behiç Gürcihan"
                        },
                        new
                        {
                            YazarID = 13,
                            YazarAdi = "Fatma Sibel Yüksek"
                        });
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Yazi", b =>
                {
                    b.Property<int>("YaziId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YaziId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YaziId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YaziBaslik");

                    b.Property<short>("Okunma")
                        .HasColumnType("smallint")
                        .HasColumnName("YaziOkunma");

                    b.Property<string>("OnIzlemeMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YaziOnIzlemeMetni");

                    b.Property<bool>("Onay")
                        .HasColumnType("bit")
                        .HasColumnName("YaziOnay");

                    b.Property<string>("TamMetin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YaziTamMetin");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("YaziTarih");

                    b.Property<int>("YazarId")
                        .HasColumnType("int")
                        .HasColumnName("YaziYazarId");

                    b.Property<bool>("YorumaAcikMi")
                        .HasColumnType("bit")
                        .HasColumnName("YaziYorumaAcikMi");

                    b.HasKey("YaziId");

                    b.HasIndex("YazarId");

                    b.ToTable("Yazi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Haber", b =>
                {
                    b.HasOne("AcikIstihbarat.API.Models.Entities.HaberKategori", "Kategori")
                        .WithMany("Haberler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.HaberKategori", b =>
                {
                    b.HasOne("AcikIstihbarat.API.Models.Entities.HaberKategori", "ParentKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentKategori");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.HaberMedya", b =>
                {
                    b.HasOne("AcikIstihbarat.API.Models.Entities.Haber", "Haber")
                        .WithMany("Medyalar")
                        .HasForeignKey("HaberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikIstihbarat.API.Models.Entities.Medya", "Medya")
                        .WithMany("Haberler")
                        .HasForeignKey("MedyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Haber");

                    b.Navigation("Medya");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Yazi", b =>
                {
                    b.HasOne("AcikIstihbarat.API.Models.Entities.Yazar", "Yazar")
                        .WithMany("Yazilar")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Haber", b =>
                {
                    b.Navigation("Medyalar");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.HaberKategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Haberler");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Medya", b =>
                {
                    b.Navigation("Haberler");
                });

            modelBuilder.Entity("AcikIstihbarat.API.Models.Entities.Yazar", b =>
                {
                    b.Navigation("Yazilar");
                });
#pragma warning restore 612, 618
        }
    }
}
